# Generated by Django 5.0.2 on 2025-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojt_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profiles/'),
        ),
    ]
