# Generated by Django 5.0.2 on 2025-05-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojt_tracker', '0002_faculty_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_time_in',
            field=models.TimeField(blank=True, help_text='Break end time', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_time_out',
            field=models.TimeField(blank=True, help_text='Break start time', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used for check-in', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_location',
            field=models.CharField(blank=True, help_text='Location/address when checking in', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used for check-out', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location',
            field=models.CharField(blank=True, help_text='Location/address when checking out', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expected_check_in',
            field=models.TimeField(default='08:00:00', help_text='Expected check-in time'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Marked as late if check-in is after expected time'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_break_minutes',
            field=models.IntegerField(default=0, help_text='Total break time in minutes'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('excused', 'Excused'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='present', max_length=20),
        ),
    ]
