# Generated by Django 5.0.2 on 2025-05-31 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojt_tracker', '0003_attendance_break_time_in_attendance_break_time_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('desired_start_date', models.DateField()),
                ('desired_end_date', models.DateField()),
                ('objective', models.TextField(help_text='Your objective for this OJT placement')),
                ('skills_to_develop', models.TextField(help_text='Skills you want to develop during OJT')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_comments', models.TextField(blank=True, help_text='Faculty comments on the request')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('total_hours_required', models.PositiveIntegerField(default=400)),
                ('company_contact_person', models.CharField(max_length=100)),
                ('company_contact_email', models.EmailField(max_length=254)),
                ('company_contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_requests', to='ojt_tracker.company')),
                ('preferred_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_supervisions', to='ojt_tracker.faculty')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='ojt_tracker.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_requests', to='ojt_tracker.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'company', 'desired_start_date')},
            },
        ),
    ]
