# Generated by Django 5.0.2 on 2025-05-31 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojt_tracker', '0004_ojtrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ojtrequest',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.RenameField(
            model_name='ojtrequest',
            old_name='created_at',
            new_name='date_submitted',
        ),
        migrations.AlterUniqueTogether(
            name='ojtrequest',
            unique_together={('student', 'status')},
        ),
        migrations.AddField(
            model_name='ojtrequest',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Admin response or feedback for the request'),
        ),
        migrations.AddField(
            model_name='ojtrequest',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks or additional information about the OJT request'),
        ),
        migrations.AlterField(
            model_name='ojtrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ojt_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ojtrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='company_contact_email',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='company_contact_person',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='company_contact_phone',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='desired_end_date',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='desired_start_date',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='faculty_comments',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='position',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='preferred_supervisor',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='skills_to_develop',
        ),
        migrations.RemoveField(
            model_name='ojtrequest',
            name='total_hours_required',
        ),
    ]
