# Generated by Django 5.0.2 on 2025-05-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojt_tracker', '0005_alter_ojtrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ojtrequest',
            unique_together=set(),
        ),
    ]
